#!/usr/bin/env python3
# scripts/make_prod_config.py - Bake prod endpoint into the add-on (dev only).
"""Generates evolved/prod_config.py from explicit inputs at BUILD time.

The public anon key MAY ship (it is a publishable client key, gated by RLS);
the service-role/SMTP/admin keys MUST NEVER ship. This script takes ONLY the
anon key + URL, writes a two-constant module, and refuses to run when given
anything resembling a privileged key (service_role JWT, sb_secret_, SMTP
password). Run manually before the production build; never in CI unattended.

Usage:
  python3 scripts/make_prod_config.py \
    --url https://vjqzamuogcughdvzskmf.supabase.co \
    --anon-key <sb_publishable_... or anon JWT>

To clear (dev builds): python3 scripts/make_prod_config.py --clear
"""
from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEST = os.path.join(ROOT, "evolved", "prod_config.py")

FORBIDDEN_MARKERS = ("service_role", "sb_secret_", "smtp", "password",
                     "resend", "re_")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="scripts/make_prod_config.py")
    parser.add_argument("--url", default="")
    parser.add_argument("--anon-key", default="")
    parser.add_argument("--clear", action="store_true")
    args = parser.parse_args(argv)
    if args.clear:
        if os.path.exists(DEST):
            os.unlink(DEST)
            print(f"prod_config: cleared {DEST}")
        else:
            print("prod_config: already absent")
        return 0
    url = args.url.strip()
    key = args.anon_key.strip()
    if not url.startswith("https://") or not key:
        print("prod_config: ERROR: --url must be https:// and --anon-key "
              "non-empty", file=sys.stderr)
        return 2
    lowered = (url + "\n" + key).lower()
    for marker in FORBIDDEN_MARKERS:
        if marker in lowered:
            print(f"prod_config: ERROR: input looks privileged (contains "
                  f"{marker!r}); refusing to bake into the add-on. Only the "
                  f"public anon key may ship.", file=sys.stderr)
            return 2
    with open(DEST, "w", encoding="utf-8") as fh:
        fh.write('# evolved/prod_config.py - GENERATED by scripts/make_prod_config.py.\n'
                  '# Public anon key only (RLS-gated); never privileged keys.\n'
                  '# Regenerate per release; delete for dev-loop builds.\n'
                  f'SUPABASE_URL = {url!r}\n'
                  f'SUPABASE_ANON_KEY = {key!r}\n')
    print(f"prod_config: wrote {DEST} (public anon key only)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
