#!/usr/bin/env python3
"""scripts/make_ui_assets.py - Deterministic original UI assets (textures,
icons, sounds). No runtime downloads; no third-party art.

Run from the repo root:  python3 scripts/make_ui_assets.py
Overwrites generated files in place, EXCEPT anything recorded in
assets/manifest.json as verified third-party art (downloaded Wiki art) —
routine regeneration can never clobber verified files. All output bytes are
reproducible.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import struct
import wave
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Same token values as evolved/ui/theme.py (imported by path below to avoid
# a Qt dependency at generation time).
GOLD = (0xE3, 0xBE, 0x68, 255)
BORDER = (0x79, 0x67, 0x44, 255)
PANEL = (0x3A, 0x34, 0x2A, 255)
RAISED = (0x4A, 0x41, 0x33, 255)
TEXT = (0xF2, 0xE6, 0xC9, 255)
SUCCESS = (0x98, 0xC7, 0x7A, 255)
ERROR = (0xF0, 0xA0, 0x8C, 255)
INSET = (0x2A, 0x25, 0x1D, 255)
STONE = (0x21, 0x1E, 0x19, 255)
TRANSPARENT = (0, 0, 0, 0)

PIXEL = {
    ".": TRANSPARENT,
    "g": GOLD,
    "b": BORDER,
    "p": PANEL,
    "r": RAISED,
    "t": TEXT,
    "s": SUCCESS,
    "e": ERROR,
    "i": INSET,
    "k": STONE,
}

ICONS = {
    "training_icon": """
................
......ggg.......
...ggggggggg....
......ggg.......
.....bbbb.......
......bb........
......bb........
......bb........
......bb........
......bb........
......bb........
......bb........
.....bbbb.......
................
................
................
""",
    "skills_icon": """
................
................
...gg....gg.....
..gggg..gggg....
..gggg..gggg....
...gg....gg.....
................
...gg....gg.....
..gggg..gggg....
..gggg..gggg....
...gg....gg.....
................
...gg....gg.....
..gggg..gggg....
..gggg..gggg....
...gg....gg.....
""",
    "bank_icon": """
................
................
..bbbbbbbbbbbb..
..brrrrrrrrrrb..
..brrrrrrrrrrb..
..bbbbbbbbbbbb..
..bppppppppppb..
..bppppggggppb..
..bppppgggpppb..
..bppppggggppb..
..bppppppppppb..
..bppppppppppb..
..bbbbbbbbbbbb..
................
................
................
""",
    "achievements_icon": """
................
......gggg......
.....gggggg.....
....gg....gg....
....g..tt..g....
....g.t..t.g....
....gg....gg....
.....gggggg.....
......gggg......
.....gg..gg.....
....gg....gg....
...gg......gg...
...gg......gg...
...e........e...
..ee........ee..
................
""",
    "hiscores_icon": """
................
................
............gg..
...........gggg.
...........gggg.
........gg.gggg.
.......gggg.ggg.
.......gggg.gggg
...gg..gggg.gggg
..gggg.gggg.gggg
..gggg.gggg.gggg
..gggg.gggg.gggg
..gggg.gggg.gggg
..bbbb.bbbb.bbbb
................
................
""",
    "fishing_icon": """
................
................
................
................
.....ggg........
...gggggg..g....
..gggggggg.gg...
.ggggggggggggg..
.ggggggggggggg..
..gggggggg.gg...
...gggggg..g....
.....ggg........
................
................
................
................
""",
    "cooking_icon": """
................
.....t.t.t......
......t.t.......
................
....bbbbbbbb....
...bppppppppb...
..bppppppppppb..
..bppppppppppb..
..bppppppppppb..
..bppppppppppb..
..bbbbbbbbbbbb..
...gggggggggg...
................
................
................
................
""",
    "settings_icon": """
................
......gg........
...g..gg..g.....
...gg.gg.gg.....
....gggggggg....
.....gggggg.....
..g..gggggg..g..
..ggggggggggg...
..ggggggggggg...
..g..gggggg..g..
.....gggggg.....
....gggggggg....
...gg.gg.gg.....
...g..gg..g.....
......gg........
................
""",
    "arrow_left": """
................
......bb........
.....bbb........
....bbbb........
...bbbbb........
..bbbbbb........
.bbbbbbb........
.bbbbbbb........
..bbbbbb........
...bbbbb........
....bbbb........
.....bbb........
......bb........
................
................
................
""",
    "arrow_right": """
................
........bb......
........bbb.....
........bbbb....
........bbbbb...
........bbbbbb..
........bbbbbbb.
........bbbbbbb.
........bbbbbb..
........bbbbb...
........bbbb....
........bbb.....
........bb......
................
................
................
""",
    "fallback_missing": """
................
..bbbbbbbbbbbb..
..b..........b..
..b..tt....t.b..
..b..tt....t.b..
..b....tt....b..
..b...tt.....b..
..b...tt.....b..
..b...tt.....b..
..b...tt.....b..
..b..........b..
..b......tt..b..
..b......tt..b..
..bbbbbbbbbbbb..
................
................
""",
    "pause_icon": """
................
................
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
....gg....gg....
................
................
""",
    "pending_icon": """
................
...bbbbbbbbbb...
...bggggggggb...
....bggggggb....
.....bggggb.....
......bggb......
.......bb.......
.......bb.......
......bggb......
.....bggggb.....
....bggggggb....
...bggggggggb...
...bbbbbbbbbb...
................
................
................
""",
    "offline_icon": """
................
.....gggg.......
...gg....gg.....
..g........g....
..g......g.g....
.g......gg.g....
.g.....gg..g....
.g....gg...g....
.g...gg....g....
.g..gg.....g....
..g.gg.....g....
..g.gg....g.....
...gg....gg.....
.....gggg.......
........gg......
................
""",
    "report_icon": """
................
..bbbbbbbbbbbb..
..brrrrrrrrrrb..
..brrreeeerrrb..
..brrreeeerrrb..
..brrrreeerrrb..
..brrrreeerrrb..
..brrrrrrrrrrb..
..brrrreeerrrb..
..brrrreeerrrb..
..brrrrrrrrrrb..
..bbbbbbbbbbbb..
....bb..bb......
.....bbbb.......
................
................
""",
}


def _verified_paths() -> set:
    """Paths recorded as verified third-party art in the manifest."""
    path = os.path.join(ROOT, "assets", "manifest.json")
    try:
        with open(path, encoding="utf-8") as fh:
            manifest = json.load(fh)
    except (OSError, ValueError):
        return set()
    protected = set()
    for record in manifest.get("files", []):
        if not isinstance(record, dict):
            continue
        if record.get("status") == "verified" or record.get("rights") == "jagex-wiki":
            rel = str(record.get("path") or "")
            if rel:
                protected.add(rel)
    return protected


def _write_png(path: str, width: int, height: int, rows) -> None:
    """Write an 8-bit RGBA PNG. rows: list of bytes (len = width*4)."""
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))
    raw = b"".join(b"\x00" + row for row in rows)
    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    body = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header)
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(body)


def _render_icon(grid: str, scale: int = 2) -> None:
    lines = [ln for ln in grid.strip("\n").splitlines()]
    h = len(lines)
    w = max(len(ln) for ln in lines)
    rows = []
    for ln in lines:
        padded = ln.ljust(w, ".")
        row = b""
        for ch in padded:
            row += bytes(PIXEL.get(ch, TRANSPARENT)) * scale
        for _ in range(scale):
            rows.append(row)
    return w * scale, h * scale, rows


def make_icons() -> None:
    base = os.path.join(ROOT, "icon")
    protected = _verified_paths()
    for name, grid in ICONS.items():
        rel = f"icon/{name}.png"
        if rel in protected:
            print(f"asset: {rel} kept (verified download; regeneration skipped)")
            continue
        w, h, rows = _render_icon(grid)
        _write_png(os.path.join(base, f"{name}.png"), w, h, rows)
        print(f"asset: icon/{name}.png ({w}x{h})")


def make_texture() -> None:
    """Subtle stone noise: deterministic hash per pixel, low contrast so it
    never fights legibility (long instructions sit on plain panels)."""
    size = 64
    rows = []
    for y in range(size):
        row = b""
        for x in range(size):
            seed = hashlib.sha256(f"ankiscape-stone:{x}:{y}".encode()).digest()
            n = seed[0] / 255.0
            n2 = seed[1] / 255.0
            tint = (n - 0.5) * 10.0
            blotch = 4.0 if ((x // 8) + (y // 8)) % 3 == 0 and n2 > 0.6 else 0.0
            r = int(max(0, min(255, STONE[0] + tint - blotch)))
            g = int(max(0, min(255, STONE[1] + tint - blotch)))
            b = int(max(0, min(255, STONE[2] + tint - blotch)))
            row += bytes((r, g, b, 255))
        rows.append(row)
    _write_png(os.path.join(ROOT, "textures", "stone.png"), size, size, rows)
    print(f"asset: textures/stone.png ({size}x{size})")


def _square(freq: float, seconds: float, sample_rate: int, volume: float = 0.32):
    total = int(seconds * sample_rate)
    out = []
    for i in range(total):
        t = i / sample_rate
        phase = (freq * t) % 1.0
        sample = volume if phase < 0.5 else -volume
        # Short attack/release so notes do not click.
        env = min(1.0, i / (sample_rate * 0.005),
                  (total - i) / (sample_rate * 0.01))
        out.append(int(max(-1.0, min(1.0, sample * env)) * 32767))
    return out


def _write_wav(path: str, samples, sample_rate: int = 22050) -> None:
    digits = struct.pack("<" + "h" * len(samples), *samples)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with wave.open(path, "wb") as fh:
        fh.setnchannels(1)
        fh.setsampwidth(2)
        fh.setframerate(sample_rate)
        fh.writeframes(digits)


def _silence(seconds: float, sample_rate: int):
    return [0] * int(seconds * sample_rate)


def make_sounds() -> None:
    rate = 22050
    # Level-up: C5-E5-G5 triangle-ish arpeggio (short, coalesced upstream).
    level = (_square(523.25, 0.10, rate) + _square(659.25, 0.10, rate)
             + _square(783.99, 0.20, rate))
    _write_wav(os.path.join(ROOT, "sounds", "level_up.wav"), level, rate)
    # Unlock: two bright notes with a small sparkle tail.
    unlock = (_square(880.0, 0.08, rate) + _square(1174.66, 0.08, rate)
              + _silence(0.03, rate) + _square(1567.98, 0.12, rate, volume=0.24))
    _write_wav(os.path.join(ROOT, "sounds", "unlock.wav"), unlock, rate)
    print("asset: sounds/level_up.wav, sounds/unlock.wav")


def main() -> int:
    make_icons()
    make_texture()
    make_sounds()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
